*   과제
   
> 과제 1) 특정 조건을 만족하는 Array 생성한뒤 shape print하기

>> 조건1) 1열은 0과 1사이의 균등분포에서 추출된 난수로 구성된 10개의 행으로 구성
>> 조건2) 2열은 표준 정규 분포에서 추출된 난수로 구성된 10개의 행으로 구성

>> Hint) 
>> step1) 균등분포 및 표준 정규 분포에서 난수 생성 한뒤 각각의 array의 shape을 10행 1열로 바꿈
>> step2) 각 array를 concate 시킴

>> 평가기준) concate시킨 array의 shape이 10행 2열을 만족할 것

> 과제 2) 과제1을 통해 생성된 array를 열 기준으로 평균과 표준편차를 구할 것

>> Hint) 출력된 값이 균등분포의 평균 및 표준 정규 분포의 평균과 유사 해야함.


#과제 1

In [1]:
import numpy as np

In [22]:
arr1=np.random.rand(10)
arr1=arr1.reshape([10,1])
print(arr1)
print(arr1.shape)

[[0.34882345]
 [0.66765788]
 [0.23533262]
 [0.64680477]
 [0.73542553]
 [0.02997652]
 [0.1723011 ]
 [0.24709279]
 [0.30176393]
 [0.29845501]]
(10, 1)


In [23]:
arr2=np.random.randn(10)
arr2=arr2.reshape([10,1])
print(arr2)
print(arr2.shape)

[[ 0.28643589]
 [ 0.07512309]
 [ 0.81007469]
 [-0.53672352]
 [ 0.07916268]
 [ 0.28759643]
 [ 0.83400719]
 [ 1.34969246]
 [-0.75991861]
 [-0.61013773]]
(10, 1)


In [30]:
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)
print(arr.shape)

[[ 0.34882345  0.28643589]
 [ 0.66765788  0.07512309]
 [ 0.23533262  0.81007469]
 [ 0.64680477 -0.53672352]
 [ 0.73542553  0.07916268]
 [ 0.02997652  0.28759643]
 [ 0.1723011   0.83400719]
 [ 0.24709279  1.34969246]
 [ 0.30176393 -0.75991861]
 [ 0.29845501 -0.61013773]]
(10, 2)


#과제 2

In [29]:
#array 열 기준 평균
print(np.mean(arr, axis=0))

#array 열 기준 표준편차
print(np.std(arr, axis=0))

[0.36836336 0.18153126]
[0.22291158 0.65256468]
